// API CALL 재시도 가능한 HTTP Status Codes
export const HTTP_STATUS_CODES = {
  // Client Error 상태 코드
  REQUEST_TIMEOUT: 408,
  PAYLOAD_TOO_LARGE: 413,
  TOO_MANY_REQUESTS: 429,

  // Server Error 상태 코드
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const RETRYABLE_STATUS_CODES = [
  HTTP_STATUS_CODES.REQUEST_TIMEOUT,
  HTTP_STATUS_CODES.PAYLOAD_TOO_LARGE,
  HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
  HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
  HTTP_STATUS_CODES.BAD_GATEWAY,
  HTTP_STATUS_CODES.SERVICE_UNAVAILABLE,
  HTTP_STATUS_CODES.GATEWAY_TIMEOUT,
]; 